<?php
	include_once('includePedigree\head.php');

	$fromPage= $_GET['fromPage'];
	$targetPage = "home.php";

	$id2 = $_GET['id'];
		 		
	
	echo '<script type="text/javascript">';	
	echo '$( document ).ready(function() {';	
	$query = "Select * from dogs WHERE id =".$id2;
	$request2 = exec_query(DBNAME,$query);
	while($row2 = mysqli_fetch_array($request2)){
		echo '   generatePedigree("'.$row2['df'].'","'.$row2['dm'].'");';	
	}
	echo '});';
	echo '</script>';
	echo '<style type="text/css" media="print">';
	echo '  @page { size: landscape; }';
	echo '</style>';
	echo '<style type="text/css">';
	echo '  .fullHeight{ height: auto !important;}';
	echo '</style>';

	print("<div style=\"margin:10px;\">");
	print("<div style=\"display:inline-block;float:right\"><a href=\"view.php?fromPage=".$fromPage."&id=".$_GET['id']."\">Back</a><br/><br/></div>");
	print("</div>");
	print("<div style=\"margin:40px;\">");

		 	if(!empty($_GET['id'])){
		 		$id = $_GET['id'];
		 		$id_exists = true;
		 		
				$query = "Select * from dogs WHERE id =".$id;
				$request = exec_query(DBNAME,$query);
				while($row = mysqli_fetch_array($request)){
		
print("    <div class=\"pedigree\">");
print("        <div class=\"container\">");
print("            <header>");
print("                <h1>pedigree certificate</h1>");
print("                <p class=\"header-slogan\">société du chien de berger allemand</p>");
print("            </header>");
print("            <!-- form 1 first column -->");
print("            <div class=\"details\">");
print("                <form class=\"general-details\">");
print("                    <div class=\"form-grid\">");
print("                        <label for=\"name\">Name of German Shepherd:</label>");
print("                        <input class=\"general-details-input\" type=\"text\" value=".$row['dn']." id=\"name\">");
print("");
print("                        <label for=\"registration\">Registration Nr.:</label>");
print("                        <input class=\"general-details-input\" type=\"text\" value=".$row['drn']." id=\"registration\">");
print("");
print("                        <label for=\"dateofbirth\">Date of Birth:</label>");
print("                        <input class=\"general-details-input\" type=\"text\" id=\"dateofbirth\" value=".$row['dob'].">");
print("");
print("                        <label for=\"breeder\">Breeder:</label>");
print("                        <input class=\"general-details-input\" type=\"text\" id=\"breeder\" value=".$row['db'].">");
print("");
print("                        <label for=\"owner\">Owner:</label>");
print("                        <input class=\"general-details-input\" type=\"text\" id=\"owner\" value=".$row['owner'].">");
print("");
print("                        <label for=\"coowner\">Co-Owner:</label>");
print("                        <input class=\"general-details-input\" type=\"text\" id=\"coowner\" value=\" N/A \">");
print("                    </div>");
print("                    <!-- form 1 second column -->");
print("                    <div class=\"form-grid\">");
print("");
print("                        <label for=\"gender\">Gender:</label>");
print("                        <input class=\"general-details-input\" type=\"text\" id=\"gender\" value=".$row['dg'].">");
print("");
print("                        <label for=\"microchip\">Microchip:</label>");
print("                        <input class=\"general-details-input\" type=\"text\" id=\"microchip\" value=".$row['mn'].">");
print("");
print("                        <label for=\"color\">Color & Markings:</label>");
print("                        <input class=\"general-details-input\" type=\"text\" id=\"color\" value=".$row['hc'].">");
print("");
print("                        <label for=\"cType\">Coat Type:</label>");
print("                        <input class=\"general-details-input\" type=\"text\" id=\"cType\" value=".$row['dc'].">");
print("");
print("                        <label for=\"bAddress\">Breeder's Address:</label>");
print("                        <input class=\"general-details-input\" type=\"text\" id=\"bAddress\" value=".$row['badd'].">");
print("");
print("                        <label for=\"oAddress\">Owner's Address:</label>");
print("                        <input class=\"general-details-input\" type=\"text\" id=\"oAddress\" value=".$row['oadd'].">");
print("");
print("                    </div>");
print("                </form>");
print("            </div>");

print("            <div class=\"grid-table\">");
print("                <!-- section 1 -->");
print("                <div class=\"box box1\">");
print("                    <label>Sire:</label>");
print("                    <div class=\"box-header\">");
print("                        <input readonly class=\"input-head\" type=\"text\" name=\"maleGen\" id=\"maleGen\" value='".$row['df']."'>");
print("                        <input readonly class=\"input-head-rg\" type=\"text\" name=\"maleGenDrn\" id=\"maleGenDrn\" value='".$row['drn']."'>");
print("                    </div>");
print("                    <input readonly type=\"text\" name=\"maleGenkkl\" id=\"maleGenkkl\" value='".$row['kkl']."'>");
print("                    <div class=\"box-footer\">");
print("                        <input readonly class=\"input-foot\" type=\"text\" name=\"maleGened\" id=\"maleGened\" value='".$row['ed']."'>");
print("                        <input readonly class=\"input-foot\" type=\"text\" name=\"maleGenhd\" id=\"maleGenhd\" value='".$row['hd']."'>");
print("                        <input readonly class=\"input-foot\" type=\"text\" name=\"maleGendna\" id=\"maleGendna\" value='".$row['dna']."'>");
print("                    </div>");
print("                </div>");
print("");
print("                <div class=\"box box2\">");
print("                    <label>Dam:</label>");
print("                    <div class=\"box-header\">");
print("                        <input readonly class=\"input-head\" type=\"text\" name=\"femaleGen\" id=\"femaleGen\" value=''>");
print("                        <input readonly class=\"input-head-rg\" type=\"text\" name=\"femaleGenDrn\" id=\"femaleGenDrn\" value=''>");
print("                    </div>");
print("                    <input readonly type=\"text\" name=\"femaleGenkkl\" id=\"femaleGenkkl\" value=''>");
print("                    <div class=\"box-footer\">");
print("                        <input readonly class=\"input-foot\" type=\"text\"  name=\"femaleGened\" id=\"femaleGened\" value=''>");
print("                        <input readonly class=\"input-foot\" type=\"text\" name=\"femaleGenhd\" id=\"femaleGenhd\" value=''>");
print("                        <input readonly class=\"input-foot\" type=\"text\" name=\"femaleGendna\" id=\"femaleGendna\" value=''>");
print("                    </div>");
print("                </div>");
print("                <!-- section 2 -->");
print("                <div class=\"box box3\">");
print("                    <div class=\"box-header\">");
print("                        <input readonly class=\"input-head\" type=\"text\" name=\"maleGen2\" id=\"maleGen2\" value='' >");
print("                        <input readonly class=\"input-head-rg\" type=\"text\" name=\"maleGen2Drn\" id=\"maleGen2Drn\" value='' >");
print("                    </div>");
print("                    <input readonly type=\"text\" name=\"maleGen2kkl\" id=\"maleGen2kkl\" value=''>");
print("                    <div class=\"box-footer\">");
print("                        <input readonly class=\"input-foot\" type=\"text\" name=\"maleGen2ed\" id=\"maleGen2ed\" value=\"\">");
print("                        <input readonly class=\"input-foot\" type=\"text\" name=\"maleGen2hd\" id=\"maleGen2hd\" value=\"\">");
print("                        <input readonly class=\"input-foot\" type=\"text\" name=\"maleGen2dna\" id=\"maleGen2dna\" value=\"\">");
print("                    </div>");
print("                </div>");
print("");
print("                <div class=\"box box4\">");
print("                    <div class=\"box-header\">");
print("                        <input readonly class=\"input-head\" type=\"text\" name=\"femaleGen2\" id=\"femaleGen2\" value=\"\">");
print("                        <input readonly class=\"input-head-rg\" type=\"text\"  name=\"femaleGen2Drn\" id=\"femaleGen2Drn\" value=\"\">");
print("                    </div>");
print("                    <input readonly type=\"text\" name=\"femaleGen2kkl\" id=\"femaleGen2kkl\" value=''>");
print("                    <div class=\"box-footer\">");
print("                        <input readonly class=\"input-foot\" type=\"text\"  name=\"femaleGen2ed\" id=\"femaleGen2ed\" value=\"\">");
print("                        <input readonly class=\"input-foot\" type=\"text\"  name=\"femaleGen2hd\" id=\"femaleGen2hd\" value=\"\">");
print("                        <input readonly class=\"input-foot\" type=\"text\"  name=\"femaleGen2dna\" id=\"femaleGen2dna\" value=\"\">");
print("                    </div>");
print("                </div>");
print("");
print("                <div class=\"box box5\">");
print("                    <div class=\"box-header\">");
print("                        <input readonly class=\"input-head\" type=\"text\" name=\"fMaleGen2\" id=\"fMaleGen2\" value=\"\">");
print("                        <input readonly class=\"input-head-rg\" type=\"text\" name=\"fMaleGen2Drn\" id=\"fMaleGen2Drn\" value=\"\">");
print("                    </div>");
print("                    <input readonly type=\"text\" name=\"fMaleGen2kkl\" id=\"fMaleGen2kkl\" value=\"\">");
print("                    <div class=\"box-footer\">");
print("                        <input readonly class=\"input-foot\" type=\"text\" name=\"fMaleGen2ed\" id=\"fMaleGen2ed\" value=\"\">");
print("                        <input readonly class=\"input-foot\" type=\"text\" name=\"fMaleGen2hd\" id=\"fMaleGen2hd\" value=\"\">");
print("                        <input readonly class=\"input-foot\" type=\"text\" name=\"fMaleGen2dna\" id=\"fMaleGen2dna\" value=\"\">");
print("                    </div>");
print("                </div>");
print("");
print("                <div class=\"box box6\">");
print("                    <div class=\"box-header\">");
print("                        <input readonly class=\"input-head\" type=\"text\" name=\"fFemaleGen2\" id=\"fFemaleGen2\" value=\"\">");
print("                        <input readonly class=\"input-head-rg\" type=\"text\" name=\"fFemaleGen2Drn\" id=\"fFemaleGen2Drn\" value=\"\">");
print("                    </div>");
print("                    <input readonly type=\"text\" name=\"fFemaleGen2kkl\" id=\"fFemaleGen2kkl\" value=\"\">");
print("                    <div class=\"box-footer\">");
print("                        <input readonly class=\"input-foot\" type=\"text\" name=\"fFemaleGen2ed\" id=\"fFemaleGen2ed\" value=\"\">");
print("                        <input readonly class=\"input-foot\" type=\"text\" name=\"fFemaleGen2hd\" id=\"fFemaleGen2hd\" value=\"\">");
print("                        <input readonly class=\"input-foot\" type=\"text\" name=\"fFemaleGen2dna\" id=\"fFemaleGen2dna\" value=\"\">");
print("                    </div>");
print("                </div>");
print("<!-- section 3 -->");
print("                 <div class=\"box box7\">");
print("                     <div class=\"box-header-section3\">");
print("                         <input readonly class=\"input-head-section3\" type=\"text\" name=\"maleGen3a\" id=\"maleGen3a\" value=\"\">");
print("                         <input readonly class=\"input-head-section3\" type=\"text\" name=\"maleGen3aDrn\" id=\"maleGen3aDrn\" value=\"\">");
print("                         <input readonly class=\"input-head-section3\" type=\"text\" name=\"maleGen3akkl\" id=\"maleGen3akkl\" value=\"\">");
print("                     </div>");
print("                 </div>");
print(" ");
print("                 <div class=\"box box8\">");
print("                     <div class=\"box-header-section3\">");
print("                         <input readonly class=\"input-head-section3\" type=\"text\" name=\"femaleGen3a\" id=\"femaleGen3a\" value=\"\">");
print("                         <input readonly class=\"input-head-section3\" type=\"text\" name=\"femaleGen3aDrn\" id=\"femaleGen3aDrn\" value=\"\">");
print("                         <input readonly class=\"input-head-section3\" type=\"text\" name=\"femaleGen3akkl\" id=\"femaleGen3akkl\" value=\"\">");
print("                     </div>");
print("                 </div>");
print(" ");
print("                 <div class=\"box box9\">");
print("                     <div class=\"box-header-section3\">");
print("                         <input readonly class=\"input-head-section3\" type=\"text\" name=\"maleGen3b\" id=\"maleGen3b\" value=\"\">");
print("                         <input readonly class=\"input-head-section3\" type=\"text\" name=\"maleGen3bDrn\" id=\"maleGen3bDrn\" value=\"\">");
print("                         <input readonly class=\"input-head-section3\" type=\"text\" name=\"maleGen3bkkl\" id=\"maleGen3bkkl\" value=\"\">");
print("                     </div>");
print("                 </div>");
print(" ");
print("                 <div class=\"box box10\">"); 
print("                     <div class=\"box-header-section3\">");
print("                         <input readonly class=\"input-head-section3\" type=\"text\" name=\"femaleGen3b\" id=\"femaleGen3b\" value=\"\">");
print("                         <input readonly class=\"input-head-section3\" type=\"text\" name=\"femaleGen3bDrn\" id=\"femaleGen3bDrn\" value=\"\">");
print("                         <input readonly class=\"input-head-section3\" type=\"text\" name=\"femaleGen3bkkl\" id=\"femaleGen3bkkl\" value=\"\">");
print("                     </div>");
print("                 </div>");
print(" ");
print("                 <div class=\"box box11\">"); 
print("                     <div class=\"box-header-section3\">");
print("                         <input readonly class=\"input-head-section3\" type=\"text\" name=\"fmaleGen3a\" id=\"fmaleGen3a\" value=\"\">");
print("                         <input readonly class=\"input-head-section3\" type=\"text\" name=\"fmaleGen3aDrn\" id=\"fmaleGen3aDrn\" value=\"\">");
print("                         <input readonly class=\"input-head-section3\" type=\"text\" name=\"fmaleGen3akkl\" id=\"fmaleGen3akkl\" value=\"\">");
print("                     </div>");
print("                 </div>");
print(" ");
print("                 <div class=\"box box12\">"); 
print("                     <div class=\"box-header-section3\">");
print("                         <input readonly class=\"input-head-section3\" type=\"text\" name=\"ffemaleGen3a\" id=\"ffemaleGen3a\" value=\"\">");
print("                         <input readonly class=\"input-head-section3\" type=\"text\" name=\"ffmaleGen3aDrn\" id=\"ffmaleGen3aDrn\" value=\"\">");
print("                         <input readonly class=\"input-head-section3\" type=\"text\" name=\"ffmaleGen3akkl\" id=\"ffmaleGen3akkl\" value=\"\">");
print("                     </div>");
print("                 </div>");
print(" ");
print("                 <div class=\"box box13\">"); 
print("                     <div class=\"box-header-section3\">");
print("                         <input readonly class=\"input-head-section3\" type=\"text\" name=\"fmaleGen3b\" id=\"fmaleGen3b\" value=\"\">");
print("                         <input readonly class=\"input-head-section3\" type=\"text\" name=\"fmaleGen3bDrn\" id=\"fmaleGen3bDrn\" value=\"\">");
print("                         <input readonly class=\"input-head-section3\" type=\"text\" name=\"fmaleGen3bkkl\" id=\"fmaleGen3bkkl\" value=\"\">");
print("                     </div>");
print("                 </div>");
print(" ");
print("                 <div class=\"box box14\">"); 
print("                     <div class=\"box-header-section3\">");
print("                         <input readonly class=\"input-head-section3\" type=\"text\" name=\"ffemaleGen3b\" id=\"ffemaleGen3b\" value=\"\">");
print("                         <input readonly class=\"input-head-section3\" type=\"text\" name=\"ffemaleGen3bDrn\" id=\"ffemaleGen3bDrn\" value=\"\">");
print("                         <input readonly class=\"input-head-section3\" type=\"text\" name=\"ffmaleGen3akkl\" id=\"ffemaleGen3bkkl\" value=\"\">");
print("                     </div>");
print("                 </div>");
print(" ");
print(" <!-- section 4 -->");
print("                <div class=\"box box15 section4\">");
print("                    <div class=\"box-header-section4\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"maleGen3a1\" id=\"maleGen3a1\" value=\"\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"maleGen3a1Drn\" id=\"maleGen3a1Drn\" value=\"\">");
print("                    </div>");
print("                </div>");
print("                <div class=\"box box16 section4\">");
print("                    <div class=\"box-header-section4\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"femaleGen3a1\" id=\"femaleGen3a1\" value=\"\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"femaleGen3a1Drn\" id=\"femaleGen3a1Drn\" value=\"\">");
print("                    </div>");
print("                </div>");
print("                <div class=\"box box17 section4\">");
print("                    <div class=\"box-header-section4\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"maleGen3a2\" id=\"maleGen3a2\" value=\"\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"maleGen3a2Drn\" id=\"maleGen3a2Drn\" value=\"\">");
print("                    </div>");
print("                </div>");
print("                <div class=\"box box18 section4\">");
print("                    <div class=\"box-header-section4\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"femaleGen3a2\" id=\"femaleGen3a2\" value=\"\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"femaleGen3a2Drn\" id=\"emaleGen3a2Drn\" value=\"\">");
print("                    </div>");
print("                </div>");
print("                <div class=\"box box19 section4\">");
print("                    <div class=\"box-header-section4\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"maleGen3b1\" id=\"maleGen3b1\" value=\"\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"maleGen3b1Drn\" id=\"maleGen3b1Drn\" value=\"\">");
print("                    </div>");
print("                </div>");
print("                <div class=\"box box20 section4\">");
print("                    <div class=\"box-header-section4\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"femaleGen3b1\" id=\"femaleGen3b1\" value=\"\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"femaleGen3b1Drn\" id=\"femaleGen3b1Drn\" value=\"\">");
print("                    </div>");
print("                </div>");
print("                <div class=\"box box21 section4\">");
print("                    <div class=\"box-header-section4\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"maleGen3b2\" id=\"maleGen3b2\" value=\"\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"maleGen3b2Drn\" id=\"maleGen3b2Drn\" value=\"\">");
print("                    </div>");
print("                </div>");
print("                <div class=\"box box22 section4\">");
print("                    <div class=\"box-header-section4\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"femaleGen3b2\" id=\"femaleGen3b2\" value=\"\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"femaleGen3b2Drn\" id=\"femaleGen3b2Drn\" value=\"\">");
print("                    </div>");
print("                </div>");
print("                <div class=\"box box23 section4\">");
print("                    <div class=\"box-header-section4\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"fmaleGen3a1\" id=\"fmaleGen3a1\" value=\"\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"fmaleGen3a1Drn\" id=\"fmaleGen3a1Drn\" value=\"\">");
print("                    </div>");
print("                </div>");
print("                <div class=\"box box24 section4\">");
print("                    <div class=\"box-header-section4\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"ffemaleGen3a1\" id=\"ffemaleGen3a1\" value=\"\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"ffemaleGen3a1Drn\" id=\"ffemaleGen3a1Drn\" value=\"\">");
print("                    </div>");
print("                </div>");
print("                <div class=\"box box25 section4\">");
print("                    <div class=\"box-header-section4\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"fmaleGen3a2\" id=\"fmaleGen3a2\" value=\"\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"fmaleGen3a2Drn\" id=\"fmaleGen3a2Drn\" value=\"\">");
print("                    </div>");
print("                </div>");
print("                <div class=\"box box26 section4\">");
print("                    <div class=\"box-header-section4\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"ffemaleGen3a2\" id=\"ffemaleGen3a2\" value=\"\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"ffemaleGen3a2Drn\" id=\"ffemaleGen3a2Drn\" value=\"\">");
print("                    </div>");
print("                </div>");
print("                <div class=\"box box27 section4\">");
print("                    <div class=\"box-header-section4\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"fmaleGen3b1\" id=\"fmaleGen3b1\" value=\"\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"fmaleGen3b1Drn\" id=\"fmaleGen3b1Drn\" value=\"\">");
print("                    </div>");
print("                </div>");
print("                <div class=\"box box28 section4\">");
print("                    <div class=\"box-header-section4\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"ffemaleGen3b1\" id=\"ffemaleGen3b1\" value=\"\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"ffemaleGen3b1Drn\" id=\"ffemaleGen3b1Drn\" value=\"\">");
print("                    </div>");
print("                </div>");
print("                <div class=\"box box29 section4\">");
print("                    <div class=\"box-header-section4\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"fmaleGen3b2\" id=\"fmaleGen3b2\" value=\"\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"fmaleGen3b2Drn\" id=\"fmaleGen3b2Drn\" value=\"\">");
print("                    </div>");
print("                </div>");
print("                <div class=\"box box30 section4\">");
print("                    <div class=\"box-header-section4\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"ffemaleGen3b2\" id=\"ffemaleGen3b2\" value=\"\">");
print("                        <input readonly class=\"input-head-section4\" type=\"text\" name=\"ffemaleGen3b2Drn\" id=\"ffemaleGen3b2Drn\" value=\"\">");
print("                    </div>");
print("                </div>");
print("          </div>");
print(" <!-- footer -->");
print("");
print("            <footer>");
print("                <div class=\"logo-footer\">");
print("                    <img src=\"./includePedigree/images/logo-2.png\" alt=\"\">");
print("                    <img src=\"./includePedigree/images/logo-1.png\" alt=\"\">");
print("                </div>");
print("                <div class=\"footer-details\">");
print("                    <div class=\"date-sig\">");
print("                        <span class=\"date\">Issue Date </span>");
print("                        <span class=\"signature\">Signature</span>");
print("                    </div>");
print("                    <p>We certify that to the best of our knowledge the informaiton is correct.</p>");
print("                </div>");
print("            </footer>");
print("        </div>");
print("    </div>");

Print "<input type=\"hidden\" name=\"id\" id=\"id\" value=".$id.">";
Print "<input type=\"hidden\" name=\"fromPage\" id=\"fromPage\" value=".$fromPage.">";
Print "<input type=\"hidden\" name=\"changedInputs\" id=\"changedInputs\">";
		
print("    </div>");
}
				
			}
	print("</div>");
			
			
		?>
<?php
	include_once('includePedigree\foot.php');
?>
